name: first_workflow
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }} # script-file key name. Will be an output of the job to use it in another job
    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Publish JS filename
        id: publish  # used in steps.publish.outputs.script-file
        run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'  # '::set-output name=script-file::{}' - old syntax. script-file=anyValue

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: |
            dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files

      - name: Output contents
        run: ls

      - name: Output filename
        run: echo '${{ needs.build.outputs.script-file }}' # accessing job output

      - name: Deploy application
        run: |
          echo "Deploying application"
          echo "Deployed successfully"